name: Run Selenium Tests

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          # Extract the first two parts of the Chrome version
          CHROME_VERSION=$(google-chrome --version | sed -E 's/[^0-9]*([0-9
