name: CI for SkillMatching

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Java (assuming Java 11)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Chrome browser
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Set up ChromeDriver with the closest version to the installed Chrome version
      - name: Setup ChromeDriver
        run: |
          # Get Chrome major and minor version
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+")
          
          # Fetch compatible ChromeDriver version for this Chrome version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
          # If no version is found, default to latest ChromeDriver release
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          # Download and setup ChromeDriver
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Cache dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up Maven
      - name: Set up Maven
        run: |
          mvn --version

      # Install dependencies and run tests
      - name: Build and Test with Maven
        run: |
          mvn clean install -DskipTests=false
        env:
          DISPLAY: :99.0  # Required for headless Chrome
