name: Run Selenium Tests

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          - name: Setup ChromeDriver
          run: |
            # Get Chrome major and minor version
            CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+")
        
            # Fetch compatible ChromeDriver version for this Chrome version
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        
            # If no version is found, default to latest ChromeDriver release
            if [ -z "$CHROMEDRIVER_VERSION" ]; then
              CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
            fi
        
            # Download and setup ChromeDriver
            wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip -d /tmp/
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
          shell: bash

      - name: Install Dependencies
        run: mvn install

      - name: Run Selenium Tests with Chrome
        run: mvn test -Dbrowser=chrome
        env:
          DISPLAY: :99
          
      - name: Run Selenium Tests with Firefox (if needed)
        run: mvn test -Dbrowser=firefox
        env:
          DISPLAY: :99

      # Optionally, you can add a step for Safari if running on macOS
      # You may want to conditionally include this based on the OS.
