name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Check out code
      uses: actions/checkout@v2

    # Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install dependencies and build
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Set up ChromeDriver
    - name: Setup ChromeDriver
      run: |
        # Get the major and minor version of Chrome installed
        CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+")
        
        # Fetch the compatible ChromeDriver version for the current Chrome version
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        
        # If no specific version is found, use the latest release as a fallback
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "No specific ChromeDriver version found for Chrome version $CHROME_VERSION, falling back to the latest version."
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        fi

        # Download and setup ChromeDriver
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O chromedriver_linux64.zip
        if [ $? -ne 0 ]; then
          echo "Error downloading ChromeDriver. Exiting."
          exit 1
        fi

        unzip chromedriver_linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
      shell: /usr/bin/bash -e {0}
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.24-8/x64
        JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.24-8/x64

    # Run tests
    - name: Run tests with Maven
      run: mvn test
